bots/urls.py
from django.urls import path

from bots import views

app_name = 'bots'
urlpatterns = [
    path('', views.bot_list, name='bot-list'),
    path('battle-history-csv/', views.battle_history_csv, name='battle_history_csv'),
    path('battle-history-xlsx/', views.battle_history_xlsx, name='battle_history_xlsx'),
    path('battle-history-xlsx-pvp/', views.battle_history_xlsx_pvp, name='battle_history_xlsx_pvp'),
    path('tick/', views.execute_tick, name='tick'),
    path('init-bot/', views.init, name='init'),
    path('activate/<int:bot_id>/', views.activate, name='activate'),
    path('return-cs/<int:bot_id>/', views.return_cs, name='return_cs'),
    path('retire/<int:bot_id>/', views.retire, name='retire'),
    path('post-bounties/<int:bot_id>/', views.bounties, name='post_bounties'),
    path('battle-history/', views.battle_history_list, name='battle_history_list'),
    path('battle-history/<int:battle_history_id>/', views.battle_history_detail, name='battle_history_detail'),
]

bots/views.py
import csv
import io
from datetime import timedelta
from typing import List

import xlsxwriter
from django.conf import settings
from django.db import connection
from django.db.models import Q
from django.http import HttpResponse
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404, render
from django.utils import timezone
from django.views.decorators.http import require_POST

from bots.core import initialize_bot, activate_bot, retire_bot, return_possible_cs, calculate_max_bot_count, \
    post_bounties
from bots.format import sanitize_regent
from bots.models import Bot, BattleHistory, BattleHistoryUnits
from bots.tick import tick


# noinspection DuplicatedCode
def bot_list(request):
    bots = Bot.objects \
        .select_related('army', 'combat_spell_settings') \
        .order_by('-active', 'expires_returns_at', 'id').all()

    with connection.cursor() as cursor:
        cursor.execute("""SELECT utoky.kdo,
       utoky.koho,
       utoky.kdy,
       utoky.ztraty_kdo,
       utoky.ztraty_koho,
       utoky.zabrano_har,
       utoky.sila_utocnika,
       utoky.sila_obrance,
       utoky.protiutok_pouzito,
       users.spravce,
       users.provincie,
       aliance.nazev_aliance
FROM utoky
LEFT JOIN users ON users.id = utoky.kdo
LEFT JOIN aliance ON users.id_aliance = aliance.id_aliance
WHERE utoky.koho IN (SELECT ma_province_id FROM bots_bot)
  AND utoky.je_to_prvoutok = 1
  AND kdy > %s
ORDER BY utoky.kdy DESC""", [(timezone.now() - timedelta(hours=48)).timestamp()])

        columns = [col[0] for col in cursor.description]
        defenses = [
            dict(zip(columns, row))
            for row in cursor.fetchall()
        ]

    with connection.cursor() as cursor:
        cursor.execute("""SELECT utoky.kdo,
       utoky.koho,
       utoky.kdy,
       utoky.ztraty_kdo,
       utoky.ztraty_koho,
       utoky.zabrano_har,
       utoky.sila_utocnika,
       utoky.sila_obrance,
       utoky.protiutok_pouzito,
       users.spravce,
       users.provincie,
       aliance.nazev_aliance
FROM utoky
LEFT JOIN users ON users.id = utoky.koho
LEFT JOIN aliance ON users.id_aliance = aliance.id_aliance
WHERE utoky.kdo IN (SELECT ma_province_id FROM bots_bot)
  AND kdy > %s
ORDER BY utoky.kdy DESC""", [(timezone.now() - timedelta(hours=48)).timestamp()])

        columns = [col[0] for col in cursor.description]
        attacks = [
            dict(zip(columns, row))
            for row in cursor.fetchall()
        ]

    combats_by_bot_ma_id = {}

    for combat in defenses:
        key = combat['koho']
        combat['is_defense'] = True
        combat['ztraty_kdo'] = int(combat['ztraty_kdo'] / 100)
        combat['ztraty_koho'] = int(combat['ztraty_koho'] / 100)
        combat['spravce'] = sanitize_regent(combat['spravce'])
        if key not in combats_by_bot_ma_id:
            combats_by_bot_ma_id[key] = []

        combats_by_bot_ma_id[key].append(combat)

    for combat in attacks:
        key = combat['kdo']
        combat['is_defense'] = False
        combat['ztraty_kdo'] = int(combat['ztraty_kdo'] / 100)
        combat['ztraty_koho'] = int(combat['ztraty_koho'] / 100)
        combat['spravce'] = sanitize_regent(combat['spravce'])
        if key not in combats_by_bot_ma_id:
            combats_by_bot_ma_id[key] = []

        combats_by_bot_ma_id[key].append(combat)

    for combat in combats_by_bot_ma_id.values():
        combat.sort(key=lambda c: -c['kdy'])

    return render(request, 'bots/bot_list.html', {
        'bots': bots,
        'combats_by_bot_ma_id': combats_by_bot_ma_id,
        'show_admin_info': settings.BOTS_SHOW_ADMIN_INFO,
        'ui_background': settings.BOTS_UI_BACKGROUND,
        'max_bot_count': calculate_max_bot_count(),
        'active_bot_count': len(Bot.objects.filter(active=True)),
    })


def battle_history_list(request):
    all_bots = list(Bot.objects.all())
    bot_ma_ids = list(bot.ma_province_id for bot in all_bots)

    battles = BattleHistory.objects.filter(Q(id_attacker__in=bot_ma_ids) | Q(id_defender__in=bot_ma_ids)) \
        .order_by('-battle_timestamp') \
        .all()  # type: List[BattleHistory]

    return render(request, 'bots/battle_history_list.html', {
        'battles': battles,
        'bot_ids': set(bot_ma_ids),
        # 'bots': all_bots.
    })


def battle_history_detail(request, battle_history_id):
    all_bots = list(Bot.objects.all())
    bot_ma_ids = list(bot.ma_province_id for bot in all_bots)

    battle = get_object_or_404(BattleHistory.objects
                               .filter(Q(id_attacker__in=bot_ma_ids) | Q(id_defender__in=bot_ma_ids),
                                       id=battle_history_id))  # type: BattleHistory

    units = list(BattleHistoryUnits.objects.filter(id_battle_history=battle_history_id).all())
    attacker_units = list(unit for unit in units if unit.is_attacker == 1)  # type: List[BattleHistoryUnits]
    defender_units = list(unit for unit in units if unit.is_attacker != 1)  # type: List[BattleHistoryUnits]
    attacker_units.sort(key=lambda u: [u.support_id if u.support_id is not None else 0, - u.count_original * u.power])
    defender_units.sort(key=lambda u: [u.support_id if u.support_id is not None else 0, - u.count_original * u.power])

    return render(request, 'bots/battle_history_detail.html', {
        'battle': battle,
        'attacker_units': attacker_units,
        'defender_units': defender_units,
    })


@require_POST
def execute_tick(request):
    if not settings.BOTS_SHOW_ADMIN_INFO:
        return HttpResponseForbidden('Forbidden')

    tick()

    return redirect('bots:bot-list')


@require_POST
def init(request):
    if not settings.BOTS_SHOW_ADMIN_INFO:
        return HttpResponseForbidden('Forbidden')

    initialize_bot()

    return redirect('bots:bot-list')


@require_POST
def activate(request, bot_id: int):
    if not settings.BOTS_SHOW_ADMIN_INFO:
        return HttpResponseForbidden('Forbidden')

    bot = get_object_or_404(Bot, id=bot_id)
    activate_bot(bot)

    return redirect('bots:bot-list')


@require_POST
def return_cs(request, bot_id: int):
    if not settings.BOTS_SHOW_ADMIN_INFO:
        return HttpResponseForbidden('Forbidden')

    bot = get_object_or_404(Bot, id=bot_id)
    return_possible_cs(bot)

    return redirect('bots:bot-list')


@require_POST
def retire(request, bot_id: int):
    if not settings.BOTS_SHOW_ADMIN_INFO:
        return HttpResponseForbidden('Forbidden')

    bot = get_object_or_404(Bot, id=bot_id)
    retire_bot(bot)

    return redirect('bots:bot-list')


@require_POST
def bounties(request, bot_id: int):
    if not settings.BOTS_SHOW_ADMIN_INFO:
        return HttpResponseForbidden('Forbidden')

    bot = get_object_or_404(Bot, id=bot_id)
    post_bounties(bot, force_bounty=True)

    return redirect('bots:bot-list')


def battle_history_csv(request):
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/plain; charset=utf-8')
    response['Content-Disposition'] = 'inline'

    writer = csv.writer(response)
    writer.writerow(
        ['utok id', 'utok spravce', 'obrana id', 'obrana spravce', 'prvo', 'ztraty utok', 'ztraty obrana',
         'sila utok', 'sila obrana', 'kdy', 'kdy', 'typ', 'zisk hAr', 'utok slava', 'obrana slava'])

    for row in _battle_history_data():
        writer.writerow(row)

    return response


def battle_history_xlsx(request):
    # Create an in-memory output file for the new workbook.
    output = io.BytesIO()

    # Even though the final file will be in memory the module uses temp
    # files during assembly for efficiency. To avoid this on servers that
    # don't allow temp files, for example the Google APP Engine, set the
    # 'in_memory' Workbook() constructor option as shown in the docs.
    workbook = xlsxwriter.Workbook(output)
    worksheet = workbook.add_worksheet()

    # Get some data to write to the spreadsheet.
    data = [['utok id', 'utok spravce', 'obrana id', 'obrana spravce', 'prvo', 'ztraty utok', 'ztraty obrana',
             'sila utok', 'sila obrana', 'kdy', 'kdy', 'typ', 'zisk hAr', 'utok slava',
             'obrana slava']] + _battle_history_data()

    for row_num, row in enumerate(data):
        for col_num, col in enumerate(row):
            worksheet.write(row_num, col_num, col)

    # Close the workbook before sending the data.
    workbook.close()

    # Rewind the buffer.
    output.seek(0)

    # Set up the Http response.
    filename = 'bots-%s.xlsx' % (timezone.now().strftime('%Y-%m-%d %H-%M-%S'))
    response = HttpResponse(
        output,
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
    response['Content-Disposition'] = 'attachment; filename=%s' % filename

    return response


def _battle_history_data():
    result = []

    with connection.cursor() as cursor:
        cursor.execute("""SELECT attacker.id, attacker.spravce,
           defender.id, defender.spravce,
           utoky.je_to_prvoutok,
           ROUND((1 - sila_utocnika_end / sila_utocnika)  * 100, 2),
           ROUND((1 - sila_obrance_end / sila_obrance)  * 100, 2),
           sila_utocnika,
           sila_obrance,
           kdy,
           FROM_UNIXTIME(kdy, '%Y-%m-%d %H:%i:%s'),
           battle_history.type,
           battle_history.area_taken,
           battle_history.glory_attacker,
           battle_history.glory_defender
    FROM utoky
    JOIN users AS attacker ON utoky.kdo = attacker.id
    JOIN users AS defender ON utoky.koho = defender.id
    LEFT JOIN battle_history ON utoky.battle_history_id = battle_history.id
    WHERE (attacker.is_bot = 1 OR defender.is_bot = 1)
    ORDER BY kdy""")

        while True:
            row = cursor.fetchone()
            if row is None:
                break

            row = list(row)

            row[1] = sanitize_regent(row[1])
            row[3] = sanitize_regent(row[3])

bots/templates/bots/battle_history_list.html
{% extends 'bots/layout.html' %}
{% load bots_filters %}
{% load battle_filters %}
{% load humanize %}

{% block title %}Battle History{% endblock %}

{% block css %}
{% endblock %}

{% block js %}
{% endblock %}

{% block h1 %}<code>Hell0 there, fell0w h00man!</code>{% endblock %}

{% block content %}

    <table class="table table-sm">
        <thead>
        <tr>
            <th rowspan="2">Datum</th>
            <th rowspan="2" class="text_left">Typ útoku</th>
            <th rowspan="2" class="text_left">Bitva</th>
            <th class="text-center" colspan="4">Útočník</th>
            <th class="text-center" colspan="4">Obránce</th>
            <th rowspan="2">Kvalita</th>
            <th class="text-center" rowspan="2">Výsledek</th>
            <th rowspan="2">hAR</th>
            <th class="text-center" colspan="2">Sláva</th>
            <th rowspan="2">Detail</th>
        </tr>
        <tr>
            <th>B.</th>
            <th>ID</th>
            <th class="text-left">Regent</th>
            <th>Síla</th>
            <th>B.</th>
            <th>ID</th>
            <th class="text-left">Regent</th>
            <th>Síla</th>
            <th>Já</th>
            <th>On</th>
        </tr>
        </thead>
        <tbody>
        {% for battle in battles %}
            <tr>
                <td class="text-right">{{ battle.battle_timestamp|timestamp_to_time|time_dm_hm }}</td>
                <td>{{ battle.type }}</td>
                <td>{% if battle.battle_quality %} {{ battle.battle_quality }} {% else %} {{ battle.gate_number }}. brána {% endif %}</td>
                <td class="text-center">{{ battle.color_attacker }}{{ battle.specialisation_attacker }}</td>
                <td class="text-right">{{ battle.id_attacker }}</td>
                <td>
                    {% if battle|is_bot_attacker:bot_ids %}<code>{{ battle.name_attacker|sanitize_regent }}</code>
                    {% else %}
                        {{ battle.name_attacker|sanitize_regent }}
                    {% endif %}
                </td>
                <td class="text-right">{{ battle.power_before_attacker|nf_thousands }}</td>
                <td class="text-center">{{ battle.color_defender }}{{ battle.specialisation_defender }}</td>
                <td class="text-right">{{ battle.id_defender }}</td>
                <td>
                    {% if battle|is_bot_attacker:bot_ids %}
                        {{ battle.name_defender|sanitize_regent }}
                    {% else %}
                        <code>{{ battle.name_defender|sanitize_regent }}</code>
                    {% endif %}
                </td>
                <td class="text-right">{{ battle.power_before_defender|nf_thousands }}</td>
                <td class="text-right">{{ battle.target_quality|floatformat:2 }}</td>
                <td class="text-center {{ battle|battle_result_class:bot_ids }}">
                    {{ battle.losses_attacker|mult:100|floatformat:2 }}% : {{ battle.losses_defender|mult:100|floatformat:2 }}%
                </td>
                <td class="text-right">
                    {% if battle|is_bot_attacker:bot_ids %}
                        {{ battle.area_taken|nf_pm }}
                    {% else %}
                        {{ battle.area_taken|nf_pm:True }}
                    {% endif %}
                </td>
                <td class="text-right">
                    {% if battle|is_bot_attacker:bot_ids %}
                        {{ battle.glory_attacker|nf_pm }}
                    {% else %}
                        {{ battle.glory_defender|nf_pm }}
                    {% endif %}
                </td>
                <td class="text-right">
                    {% if battle|is_bot_attacker:bot_ids %}
                        {{ battle.glory_defender|nf_pm }}
                    {% else %}
                        {{ battle.glory_attacker|nf_pm }}
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'bots:battle_history_detail' battle_history_id=battle.id %}">Detail</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

bots/templates/bots/bot_list.html
{% extends 'bots/layout.html' %}
{% load bots_filters %}
{% load humanize %}

{% block title %}Home{% endblock %}

{% block css %}
    <style type="text/css">
        tr.no-border-top td {
            border-top: none;
        }

        .returned-primary .regent, .returned-primary .province {
            text-decoration: line-through;
        }

        .super-army .army-label {
            font-weight: bold;
        }

        .inactive {
            color: #9a9fa2;
        }
    </style>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('#combat-toggle').click(() => $('tr.combat').toggle());
    </script>
{% endblock %}

{% block content %}
    <h1{% if ui_background %} style="background-color: {{ ui_background }}"{% endif %}>
        <code>Hell0 there, fell0w h00man!</code>
        <button class="btn btn-sm btn-secondary" id="combat-toggle">&#128737;&#9876;</button>
        <a class="btn btn-sm btn-secondary" href="{% url 'bots:battle_history_xlsx' %}">XLSX</a>
        <a class="btn btn-sm btn-secondary" href="{% url 'bots:battle_history_xlsx_pvp' %}">XLSX PvP</a>
        {{ active_bot_count }}/{{ max_bot_count }}
    </h1>

    {% if show_admin_info %}
        <div class="form-row">
            <div class="col">
                <form action="{% url 'bots:tick' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">TICK</button>
                </form>

            </div>
            <div class="col">
                <form action="{% url 'bots:init' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-secondary">Initialize new bot</button>
                </form>

            </div>
        </div>
    {% endif %}

    <table class="table table-sm my-4">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Active</th>
            <th scope="col">Color</th>
            <th scope="col">MA ID</th>
            <th scope="col">Login/Pwd</th>
            <th scope="col">Army / Spells</th>
            <th scope="col">Army power</th>
            <th scope="col">Activated</th>
            <th scope="col">Last CS</th>
            <th scope="col">Bounties</th>
            <th scope="col">Returns</th>
            {% if show_admin_info %}
                <th scope="col" colspan="3">Actions</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for bot in bots %}
            <tr class="{% if bot.army.color == 'XX' %} super-army {% endif %}{% if not bot.active %} inactive {% endif %}">
                <th scope="row">#{{ bot.id }}</th>
                <td>{{ bot.name }}</td>
                <td>
                    {% if bot.active %}
                        <span class="badge badge-success">Yes</span>
                    {% else %}
                        <span class="badge badge-light">No</span>
                    {% endif %}
                </td>
                <td><code>{{ bot.color }}</code></td>
                <td>{{ bot.ma_province_id }}</td>
                <td><code>{% if show_admin_info %}{{ bot.ma_login }}{% else %}&mdash;{% endif %}</code></td>
                <td class="army-label">{{ bot.army.label }} [{{ bot.army.id }}]</td>
                <td>{{ bot.army_power|intcomma }}</td>
                <td>{{ bot.last_activated|time_dm_hm }}</td>
                <td>{{ bot.last_cs_returned|time_dm_hm }} [{{ bot.returned_cs_count }}x]</td>
                <td>{{ bot.bounty_time_at|time_dm_hm }}</td>
                <td>{{ bot.expires_returns_at|time_dm_hm }}</td>
                {% if show_admin_info %}
                    <td>
                        <form action="{% url 'bots:activate' bot_id=bot.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-warning"{% if bot.active %} disabled{% endif %}>activate</button>
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'bots:return_cs' bot_id=bot.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-warning"{% if not bot.active %} disabled{% endif %}>CS</button>
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'bots:retire' bot_id=bot.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-warning"{% if not bot.active %} disabled{% endif %}>retire</button>
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'bots:post_bounties' bot_id=bot.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-warning"{% if not bot.active %} disabled{% endif %} title="Forces bounty (eg. 100% chance)">bounty</button>
                        </form>
                    </td>
                {% endif %}
            </tr>
            <tr class="no-border-top {% if not bot.active %} inactive {% endif %}">
                <td></td>
                <td>{{ bot.province }}</td>
                <td></td>
                <td></td>
                <td></td>
                <td><code>{% if show_admin_info %}{{ bot.ma_password }}{% else %}&mdash;{% endif %}</code></td>
                <td><small>{{ bot.combat_spell_settings.label }}</small></td>
                <td></td>
                <td><small class="text-secondary">{{ bot.last_activated|naturaltime|default_if_none:'&mdash;' }}</small></td>
                <td><small class="text-secondary">{{ bot.last_cs_returned|naturaltime|default_if_none:'&mdash;' }}</small></td>
                <td><small class="text-secondary">{{ bot.bounty_time_at|naturaltime|default_if_none:'&mdash;' }}</small></td>
                <td><small class="text-secondary">{{ bot.expires_returns_at|naturaltime|default_if_none:'&mdash;' }}</small></td>
                {% if show_admin_info %}
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                {% endif %}
            </tr>
            {% with combats_by_bot_ma_id|get_dict_item:bot.ma_province_id as combats %}
                {% for combat in combats %}
                    <tr class="no-border-top combat{% if combat.is_defense and combat.protiutok_pouzito %} returned-primary {% endif %}{% if not bot.active %} inactive {% endif %}">
                        <td><small>
                            {% if combat.is_defense %}
                                {% if combat.protiutok_pouzito %}&#9960;{% else %}&#128737;{% endif %}
                            {% else %}
                                &#9876;
                            {% endif %}
                        </small></td>
                        <td class="regent"><small>{{ combat.spravce }}</small></td>
                        <td class="province"><small>{{ combat.provincie }}</small></td>
                        <td></td>
                        <td><small>{{ combat.kdo }}</small></td>
                        <td><small>{{ combat.nazev_aliance }}</small></td>
                        <td><small>{{ combat.ztraty_kdo }}% : {{ combat.ztraty_koho }}%, gained {{ combat.zabrano_har }} hAr</small></td>
                        <td><small>{{ combat.sila_utocnika|intcomma }} vs {{ combat.sila_obrance|intcomma }}</small></td>
                        <td title="{{ combat.kdy|timestamp_to_time|time_dm_hm }}"><small>{{ combat.kdy|timestamp_to_time|naturaltime|default_if_none:'&mdash;' }}</small></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        {% if show_admin_info %}
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            {% endwith %}
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

bots/templates/bots/index.html
{% extends 'bots/layout.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Hello there, fellow hooman!</h1>
{% endblock %}

bots/templates/bots/layout.html
{% load static %}<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" crossorigin="anonymous">

    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static '/favicon.ico' %}">
    <link rel="icon" type="image/x-icon" href="{% static '/favicon.ico' %}">
    <meta name="msapplication-TileImage" content="{% static 'ms-icon-144x144.png' %}">

    <title>MA BOTS | {% block title %}{% endblock %}</title>
    {% block css %}{% endblock %}
</head>
<body>

<div class="container-fluid">
    <h1{% if ui_background %} style="background-color: {{ ui_background }}"{% endif %}>{% block h1 %}{% endblock %}</h1>
    {% block content %}{% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="//code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="//cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" crossorigin="anonymous"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" crossorigin="anonymous"></script>
{% block js %}{% endblock %}
</body>
</html>